-- 자유게시판(free_posts) 댓글 테이블. tip_comments 구조 미러링.
-- Supabase SQL Editor에서 1회 실행.

create table if not exists free_comments (
  id           bigint generated by default as identity primary key,
  post_id      bigint not null,
  content      text   not null,
  author       text   not null,
  author_guild text   default '',
  parent_id    bigint,
  created_at   timestamptz not null default now()
);

create index if not exists idx_free_comments_post on free_comments(post_id);

alter table if exists free_comments enable row level security;
